version: '2'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: book-service # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - mypostgres # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/books_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - overlay

  # Database Service (postgres)
  mypostgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=books_db
    networks:
      - overlay

# Networks to be created to facilitate communication between containers
networks:
  overlay: