# Jenkins Inbound Agent with VMware vSphere SDK, pyvmomi, OVF tool

FROM jenkins/inbound-agent

USER 0

RUN apt-get update -qqy \
  && apt-get -qqy install \
  curl \
  unzip \
  wget \
  cron \
  jq \
  git-core \
  openssh-server openssh-client \
  sshpass \
  git \
  apt-transport-https \
  init \
  python3 \
  python3-pip

RUN pip3 install vcd-cli pyvmomi

RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git

RUN pip3 install vcd-cli

# OVF tool installation. Reference from https://hub.docker.com/r/maroskukan/ovftool/
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV OVFTOOL_VERSION=4.4.0-16360108
ENV OVFTOOL_INSTALLER=VMware-ovftool-${OVFTOOL_VERSION}-lin.x86_64.bundle
# RUN echo "$OVFTOOL_INSTALLER"

RUN /bin/sh -c OVFTOOL_INSTALLER=VMware-ovftool-${OVFTOOL_VERSION}-lin.x86_64.bundle  && wget -q https://stsharedservices.blob.core.windows.net/pub/ovftool/${OVFTOOL_INSTALLER}  && wget -q https://stsharedservices.blob.core.windows.net/pub/ovftool/${OVFTOOL_INSTALLER}.sha256  && sha256sum -c ${OVFTOOL_INSTALLER}.sha256

RUN /bin/sh ${OVFTOOL_INSTALLER} -p /usr/local --eulas-agreed --required  && rm -f ${OVFTOOL_INSTALLER}*
#RUN ovftool --help

RUN which ovftool
