# Jenkins Inbound Agent with VMware vSphere SDK, pyvmomi, OVF tool, govmomi, AVI SDK

FROM jenkins/inbound-agent

USER 0

RUN apt-get update -qqy \
  && apt-get -qqy install \
  curl \
  unzip \
  wget \
  cron \
  jq \
  iputils-ping \
  git-core \
  openssh-server \
  openssh-client \
  sshpass \
  git \
  apt-transport-https \
  init \
  nmap \
  python3 \
  python3-pip

RUN nmap --version

RUN pip3 install vcd-cli \
  pyvmomi==7.0 \
  oauthlib==3.1.0 \
  paramiko==2.7.1 \
  pycparser==2.20 \
  PyHamcrest==1.9.0 \
  PyJWT==1.7.1 \
  PyNaCl==1.4.0 \
  pyOpenSSL==19.0.0 \
  PyYAML==5.3.1 \
  requests==2.22.0 \
  requests-unixsocket==0.2.0 \
  simplejson==3.16.0 \
  six==1.14.0 \
  ssh-import-id==5.10 \
  urllib3==1.25.8 \
  virtualenv==20.0.17 \
  pexpect==4.8.0 \
  avisdk==21.1.4 \
  retry==0.9.2

RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git

# OVF tool installation. Reference from https://hub.docker.com/r/maroskukan/ovftool/
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV OVFTOOL_VERSION=4.4.0-16360108
ENV OVFTOOL_INSTALLER=VMware-ovftool-${OVFTOOL_VERSION}-lin.x86_64.bundle
# RUN echo "$OVFTOOL_INSTALLER"

RUN /bin/sh -c OVFTOOL_INSTALLER=VMware-ovftool-${OVFTOOL_VERSION}-lin.x86_64.bundle  && wget -q https://stsharedservices.blob.core.windows.net/pub/ovftool/${OVFTOOL_INSTALLER}  && wget -q https://stsharedservices.blob.core.windows.net/pub/ovftool/${OVFTOOL_INSTALLER}.sha256  && sha256sum -c ${OVFTOOL_INSTALLER}.sha256

RUN /bin/sh ${OVFTOOL_INSTALLER} -p /usr/local --eulas-agreed --required  && rm -f ${OVFTOOL_INSTALLER}*
#RUN ovftool --help

# Install GOVC
RUN curl -L -o - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" | tar -C /usr/local/bin -xvzf - govc
RUN govc version -l

RUN mkdir -p /root/.ssh/ && touch /root/.ssh/known_hosts
