apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  selector:
    matchLabels:
      app: book-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - image: ysree/book-service
        name: book-service
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/postgresdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgresadmin
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin123
        ports:
        - containerPort: 8080
          protocol: TCP
          name: book-service
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
