kind: Service
apiVersion: v1
metadata:
  name: book-service
  labels:
    app: book-service
  annotations:
    service.beta.kubernetes.io/decc-load-balancer-http-backend-ports: "8080"
    service.beta.kubernetes.io/decc-load-balancer-hostname: "book-service.svc-stage.eng.vmware.com"
    service.beta.kubernetes.io/decc-load-balancer-log-level: "info"
spec:
  type: LoadBalancer
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
